### ISSUE TITLE
requirements.txt for windows has been deleted?

### ISSUE THREAD

**Issue by mufasec** [angus-y/PyIris-backdoor#13]
# How and when to create an issue

## Step 1 : Environment information where PyIris was run
- Exact OS Version
- PyIris Version
- Python Version

## Step 2 : What was done before the error
- What commands were ran before the error
- What was the state of the framework before the error (eg. How many listeners active, how many scouts connected, etc.)
- Programs running while PyIris was running
- What was modified in the framework files (If any were modified)

## Step 3 : Evidence and description
- Description of the error
- Screenshot of the error
- Raw text of the error
- Videos or gifs

## Step 4 : Miscellaneous information
- Any miscellaneous information you would like to provide, the more data provided the better

# Note : Do not create an issue if you cannot reproduce the bug, I need to be able to reproduce the bug in order to fix it

**Comment by not-sekiun** [comment]
setup/windows/requirements.txt was accidentally deleted during a master push, it is now fixed, thanks for the heads up!
