### ISSUE TITLE
How to Port forward?

### ISSUE THREAD

**Issue by BLEKERS** [angus-y/PyIris-backdoor#22]
Sorry for asking, But how to port forward the host and the listener

I tried the method of metasploit but it's not working also I used portmap to try it.

I think I will try ngrok or any port forwarding tool

Thank you for reading :)

**Comment by not-sekiun** [comment]
hey, sorry for the late response, port forwarding will depend from router to router, If you access your default gateway router through its web interface, typically the router page will provide options to enable port forwarding as per the router specifications. For PyIris to function on port forwarding just make sure that the port you are forwarding is on the machine that pyiris is running on and the port that pyiris is locally listening on.
