### ISSUE TITLE
[!]Unexpected error when bootstrapping : 'DISPLAY'

### ISSUE THREAD

**Issue by rohanraj-aipro** [angus-y/PyIris-backdoor#24]
![Error](https://user-images.githubusercontent.com/85404080/129671925-f1d36a4f-d490-4c56-967a-6d2a16907a3e.png)

**Comment by not-sekiun** [comment]
Can you provide more information about the error. In the file ISSUE_TEMPLATE.md I provided guidelines for making issues regarding bugs and errors, Things like what OS your using, or python version your on would be useful for me.

**Comment by not-sekiun** [comment]
Closed due to inactivity. @Hacker-Rohan-Raj if you provide any updates on your end I'll be glad to reopen it again.

**Comment by rohanraj-aipro** [comment]
No Updates!!
