### ISSUE TITLE
where do i find the executable name

### ISSUE THREAD

**Issue by RAFFAELE91213** [angus-y/PyIris-backdoor#39]
# How and when to create an issue

## Step 1 : Environment information where PyIris was run
- Exact OS Version
- PyIris Version
- Python Version

## Step 2 : What was done before the error
- What commands were ran before the error
- What was the state of the framework before the error (eg. How many listeners active, how many scouts connected, etc.)
- Programs running while PyIris was running
- What was modified in the framework files (If any were modified)

## Step 3 : Evidence and description
- Description of the error
- Screenshot of the error
- Raw text of the error
- Videos or gifs

## Step 4 : Miscellaneous information
- Any miscellaneous information you would like to provide, the more data provided the better

# Note : Do not create an issue if you cannot reproduce the bug, I need to be able to reproduce the bug in order to fix it

**Comment by not-sekiun** [comment]
Hi, you need to be a bit more specific, what do you mean by executable name?
